### ISSUE TITLE
Faulting module KERNELBASE.dll with exception code 0xe0434352

### ISSUE THREAD

**Issue by Aleksiv95** [microsoft/Microsoft-Win32-Content-Prep-Tool#110]
`IntuneWinAppUtil.exe` (version `6.2312.17.0`) fails to run on Windows 11 Business 22H2 (OS build `22621.2428`).

**Symptoms:**

The command prompt is closed abruptly while building the output file, and the following application error is written in the Event Viewer (Event ID 1000):

```
Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.17.0, time stamp: 0xbd225276
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2428, time stamp: 0x9223bda8
Exception code: 0xe0434352
Fault offset: 0x0000000000064ffc
Faulting process id: 0x0x2734
Faulting application start time: 0x0x1DA0F1C754A49B3
Faulting application path: C:\MASKED\IntuneWinAppUtil.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 0f67cb8a-5d05-4e12-b2f5-2379814a4af5
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Aleksiv95** [comment]
Workaround: it works when started in Command Prompt (not PowerShell).

**Comment by ahtivi** [comment]
I have similar issue but it seems to be a row of application failures

It starts with OpenConsole.exe crash
Faulting application name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade
Faulting module name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade
Exception code: 0xc0000094
Fault offset: 0x0000000000002be2
Faulting process ID: 0x0x3720
Faulting application start time: 0x0x1DA10B183F057EE
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Report ID: 2f2a86b5-bdb4-4994-833f-327b7e9a6a2f
Faulting package full name: Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

This will cause IntuneWinAppUtil.exe to be terminated
Application: IntuneWinAppUtil.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.Console.GetBufferInfo(Boolean, Boolean ByRef)
   at System.Console.get_ForegroundColor()
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteWithForegroundColor(System.ConsoleColor, System.Action)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(System.String[])
   
 The 3rd one is already reported
 Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.17.0, time stamp: 0xbd225276
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2506, time stamp: 0x5a736bb8
Exception code: 0xe0434352
Fault offset: 0x000000000006565c
Faulting process ID: 0x0x739C
Faulting application start time: 0x0x1DA10B18DF68724
Faulting application path: D:\IntunePrep\IntuneWinAppUtil.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 93d0befe-dc0e-4104-9b91-ef4fb9506475
Faulting package full name: 
Faulting package-relative application ID:

**Comment by trondr** [comment]
I confirm that version 1.8.5 (6.2312.30.0) (https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/archive/refs/tags/v1.8.5.zip) breaks our build.

We are using the PowerShell module IntuneWin32App 1.4.1 and the CmdLet New-IntuneWin32AppPackage. The CmdLet downloads the latest IntuneWinAppUtil.exe and saves it to ```%temp%\IntuneWinAppUtil.exe```, if and only if the file does not already exists. For version 6.2312.30.0 of the IntuneWinAppUtil.exe, the CmdLet gives a warning that intunewin file was not created.

```
New-IntuneWin32AppPackage -SourceFolder "$buildSetupFolder\en-us" -SetupFile "$projectName.x64.msi" -OutputFolder $artifactsFolder

WARNING: Unable to detect expected 'SomeProjectName.x64.msi.intunewin' file after IntuneWinAppUtil.exe invocation

```
**Workaround**: Download the version 1.8.4 (6.2206.38.0) (https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/archive/refs/tags/v1.8.4.zip) and save to ```%temp%\IntuneWinAppUtil.exe```. The New-IntuneWin32AppPackage Cmdlet now successfully creates IntuneWin package.

**Comment by treestryder** [comment]
I am baffled... I tried running it within CMD using the following in a one-line Powershell script and it worked as expected. Tried the same thing in our production script and it fails. This is on Windows 11 using Windows Terminal.
`cmd /c IntuneWinAppUtil.exe -?`

**Comment by Joly0** [comment]
I have a similar issue here on Windows 10 Enterprise. Tried running powershell and cmd through terminal, but crashes every time.

```Name der fehlerhaften Anwendung: IntuneWinAppUtil.exe, Version: 6.2312.17.0, Zeitstempel: 0xbd225276
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3570, Zeitstempel: 0xda674bb7
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x2aac
Startzeit der fehlerhaften Anwendung: 0x01da12233d7365d5
Pfad der fehlerhaften Anwendung: C:\masked\IntuneWinAppUtil.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: e25751d9-7b01-4115-a64d-abd6484a7928
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: ```

```Application: pwsh.exe
CoreCLR Version: 7.0.1323.51816
.NET Version: 7.0.13
Description: The application requested process termination through System.Environment.FailFast.
Message: The Win32 internal error "Kein Prozess ist am anderen Ende der Pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
Description: The process was terminated due to an unhandled exception.System.Management.Automation.Host.HostException: The Win32 internal error "Kein Prozess ist am anderen Ende der Pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
 ---> System.ComponentModel.Win32Exception (233): Kein Prozess ist am anderen Ende der Pipe.
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ConsoleControl.GetConsoleScreenBufferInfo(SafeFileHandle consoleHandle)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])```

```Name der fehlerhaften Anwendung: pwsh.exe, Version: 7.3.9.500, Zeitstempel: 0x653067fb
Name des fehlerhaften Moduls: Microsoft.PowerShell.ConsoleHost.dll, Version: 7.3.9.500, Zeitstempel: 0xa2cc9934
Ausnahmecode: 0x80131623
Fehleroffset: 0x000000000004de7b
ID des fehlerhaften Prozesses: 0x1b34
Startzeit der fehlerhaften Anwendung: 0x01da122337387697
Pfad der fehlerhaften Anwendung: C:\Program Files\PowerShell\7\pwsh.exe
Pfad des fehlerhaften Moduls: C:\Program Files\PowerShell\7\Microsoft.PowerShell.ConsoleHost.dll
Berichtskennung: 7d5b1150-d88f-4ea9-80a0-509b3e43999b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: ```

**Comment by MrV8Rumble** [comment]
Just ran into this myself, grabbed the latest exe to try and resolve it and the problem persists in both Terminal and a separate PS7 window.
It DID work successfully in CMD, so I think maybe the issue is the latest PS7 build?

**Comment by Constey** [comment]
I can confirm the same issue when having the settings set to Windows-Terminal: ![image](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/11457386/8c58d28e-3b07-46fa-9473-216b882c1d24)
Switched to consolehost works in 1.8.4 and 1.8.5

I've seen following Errors in eventlog:
`Fehlerbucket 0, Typ 5
Ereignisname: CLR20r3
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: IntuneWinAppUtil.exe
P2: 6.2206.38.0
P3: a3b9d707
P4: mscorlib
P5: 4.8.9181.0
P6: 64b85429
P7: 1693
P8: f
P9: System.IO.IOException
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1c82d6bc-1efc-4dce-a25b-5d5c9a2e95b9.tmp.WERInternalMetadata.xml

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_IntuneWinAppUtil_5ca55873cda67ad8ea5f3bad62429d18585d03a_e3c6bf7c_9f3b1e96-89fc-4d49-9e96-af79dd55e2d4

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: c167b297-1a11-4ba1-8c54-28842c34394f
Berichtstatus: 268435456
Bucket mit Hash: 0fd8dafe984b6fa0c64e81c867bf856b
CAB-Datei-Guid: 0`

`Name der fehlerhaften Anwendung: IntuneWinAppUtil.exe, Version: 6.2206.38.0, Zeitstempel: 0xa3b9d707
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.2215, Zeitstempel: 0x83983b0b
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000006531c
ID des fehlerhaften Prozesses: 0x0x531C
Startzeit der fehlerhaften Anwendung: 0x0x1DA159A247E7963
Pfad der fehlerhaften Anwendung: C:\temp\Microsoft-Win32-Content-Prep-Tool-1.8.4\IntuneWinAppUtil.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: c167b297-1a11-4ba1-8c54-28842c34394f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: `

`Anwendung: IntuneWinAppUtil.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.IOException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.Console.GetBufferInfo(Boolean, Boolean ByRef)
   bei System.Console.get_ForegroundColor()
   bei Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteWithForegroundColor(System.ConsoleColor, System.Action)
   bei Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(System.String[])

`

**Comment by x9000** [comment]
My wrapper around the app is failing as well. Same errors in the event log (See below), BUT, if I elevate my wrapper app (i.e. "Run as Administrator", it runs without issue:
As non admin
**Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.30.0, time stamp: 0xb443b0f2
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2506, time stamp: 0x5a736bb8
Exception code: 0xe0434352
Fault offset: 0x000000000006565c
Faulting process ID: 0x0x2560
Faulting application start time: 0x0x1DA161CCF4BA0B9
Faulting application path: C:\Users\PAULPR~1\AppData\Local\Temp\IntuneWinAppUtil.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 895df430-dc37-471b-b16b-d1d5c959c643
Faulting package full name: 
Faulting package-relative application ID:** 

As admin - No errors at all and package created.

**Comment by AZphanus** [comment]
I'm running into the same problem. Just wanted to add to the tally.

**Comment by SweAllanD** [comment]
Running into the same problem running, both with version 6.2312.30 and 6.2206.38 on a Win11 23H2.
This from console or PS.
Only way for success was to run IntuneWinAppUtil.exe direct from Explorer.

First error for the Console:
Faulting application name: OpenConsole.exe, version: 1.18.2311.14001, time stamp: 0x6553b16d
Faulting module name: OpenConsole.exe, version: 1.18.2311.14001, time stamp: 0x6553b16d
Exception code: 0xc0000094

Then a .Net error:
Application: IntuneWinAppUtil.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.Console.GetBufferInfo(Boolean, Boolean ByRef)
   at System.Console.get_ForegroundColor()
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteWithForegroundColor(System.ConsoleColor, System.Action)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(System.String[])
   
And finally the Application error:
Faulting application name: IntuneWinAppUtil.exe, version: 6.2206.38.0, time stamp: 0xa3b9d707
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352

**Comment by thenamelessthing** [comment]
Same situation for me!!

**Comment by ameltzer-MSFT** [comment]
#122
